name: PrestigeTokens
version: 1.2.6
main: me.zwee.prestigetokens.PrestigeTokens
author: ZweeDaLegend
depend: [PrisonRanksX]

commands: 
    pt:
      usage: /prestigetokens
      description: opens the virtual prestigeshop.


      
      
      
